name: taskzen
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # State Management
  bloc: ^9.0.0
  flutter_riverpod: ^2.6.1

  # Navigation
  go_router: ^16.0.0

  # Local Storage
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  path_provider: ^2.1.5
  
  # Utilities
  equatable: ^2.0.7
  fpdart: ^1.1.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  isar_generator: ^3.1.0
  build_runner: ^2.4.13
  bloc_test: ^10.0.0
  mocktail: ^1.0.4

dependency_overrides:
  analyzer: ^5.13.0

flutter:
  uses-material-design: true
